### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by JThiner1997** [ojaha065/translatefyer#1]

**Comment by ojaha065** [comment]
Sorry that it took me this long to notice this issue.

Turned out that Google changed things around and my Cloud Translate API key stopped working. It should be working again now.

During testing I also noticed that it still sometimes throws random errors. Exact cause is still unknown but clicking the button again usually fixes it. I'll look into this later when I have some extra time. For now I added a short notice below to buttons to inform users about this.
